# Generated by Django 4.2.7 on 2024-06-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_usermember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
