# Generated by Django 4.2.7 on 2024-06-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usermember',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usermember',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
